version: '3.8'

services:
  frontend:
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    networks:
      - messenger_network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - messenger_network

networks:
  messenger_network:
    external: true

volumes:
  certbot_etc:
  certbot_var:
